name: Deploy Vite to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

# Todas las tareas se ejecutan dentro de la carpeta 'malla'
defaults:
  run:
    working-directory: malla

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node info
        run: node -v || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: malla/package-lock.json

      - name: Show workspace
        run: |
          pwd
          ls -la
          ls -la ..

      # Si npm ci falla por peer deps/lockfile, cae a npm install
      - name: Install deps
        run: npm ci --no-audit --no-fund || npm install --no-audit --no-fund

      - name: Build
        env:
          # Vite/TS no necesitan CI=true; lo dejamos vacío para evitar rarezas
          CI: ""
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: malla/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


